name: Build Nocturne Image

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU for cross-architecture
      uses: docker/setup-qemu-action@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl zip unzip m4 genimage whois execstack

    - name: Create xbps and temp directories
      run: mkdir -p $HOME/xbps && mkdir -p $HOME/tmp && mkdir -p $HOME/tmp/image-build/ && mkskidr -p $HOME/tmp/image-build/rootfs

    - name: Run stock-files
      run: cd resources/stock-files && ./download.sh

    - name: Install xbps
      run: |
        curl -LO https://repo-default.voidlinux.org/static/xbps-static-latest.x86_64-musl.tar.xz
        tar --no-overwrite-dir --no-same-owner --no-same-permissions -xvf xbps-static-latest.x86_64-musl.tar.xz -C $HOME/xbps
        echo "$HOME/xbps/usr/bin" >> $GITHUB_PATH
        
    - name: Run build script
      run: |
        chmod +x build.sh
        ./build.sh
